/** @format */

import React from "react";
import Image from "next/image";
import { IoMdRadioButtonOn } from "react-icons/io";
import Link from "next/link";
import Head from "next/head";

function Facebowl() {
  return (
    <div className="w-full">
      <Head>
        <title>Paul | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://toppng.com/uploads/preview/alien-11569184369mxcbuyahny.png"
        />
      </Head>
      <div className="w-screen h-[30vh] lg:h-[40vh] relative">
        <div className="absolute top-0 w-full h-[30vh] lg:h-[40vh] bg-black/80 z-10" />
        <Image
          className="absolute z-[-1]"
          layout="fill"
          ƒ
          objectFit="cover"
          src="/showcases/facebowl.png"
          alt="/netflix-showcase"
        />
        <div className="absolute top-[70%] max-w-[1240px] w-full translate-y-[-50%] text-white p-4 z-10">
          <h2 className="py-2">Facebowl not Facebook</h2>
          <h3>
            TypeScript / React / Chakra UI / GraphQL / Apollo Server / Prisma /
            MySQL / Redis
          </h3>
        </div>
      </div>

      <div className="max-w-[1240px] p-2 grid lg:grid-cols-5 gap-8 pt-8 mx-6">
        <div className="lg:col-span-4">
          <p className="text-xl tracking-wider uppercase text-[#5651e5]">
            Project
          </p>
          <h2 className="py-2 text-gray-600">Overview</h2>
          <div>
            <p className="py-2 text-gray-600">
              Welcome to Facebowl, a powerful and efficient blogging website
              built using GraphQL and various modern technologies. This project
              leverages GraphQL, Apollo Server, Prisma, MySQL, Redis,
              TypeScript, and Node.js to provide a seamless and interactive
              blogging experience.
            </p>
            <h2 className="py-1 text-gray-500 text-2xl">Server Side</h2>

            <h2 className="py-2 text-gray-600 text-2xl">Features</h2>
            <ul className="list-disc ml-5">
              <li>
                Create, update, and delete data using GraphQL mutations. Utilize
                .
              </li>
              <li>
                Fetch blog posts, comments, and user data with powerful GraphQL
                queries.
              </li>
              <li>Efficiently cache frequently accessed posts using Redis.</li>
              <li>
                {" "}
                TypeScript for type-safe development and enhanced code quality.
              </li>
              <li>Securely store user passwords using bcrypt.</li>
              <li>
                Authenticate users using JSON Web Tokens (JWT). Protect
                sensitive data using environment variables
              </li>
            </ul>

            <a
              href="https://gql-blogging-website-production.up.railway.app/"
              rel="noreferrer"
              target="_blank"
            >
              <button className="px-8 py-2 mt-4 mr-8 hover:scale-105 duration-300">
                Demo
              </button>
            </a>
            <a
              href="https://github.com/pawpaw2022/gql-blogging-website"
              rel="noreferrer"
              target="_blank"
            >
              <button className="px-8 py-2 mt-4 hover:scale-105 duration-300">
                Code
              </button>
            </a>
          </div>
          <div className="mt-10">
            <h2 className="py-1 text-gray-500 text-2xl">Client Side</h2>
            <h2 className="py-2 text-gray-600 text-2xl">Features</h2>
            <ul className="list-disc ml-5">
              <li>
                User Authentication: Users can sign up, sign in, and log out
                using JWT-based authentication. Certain actions require
                authentication, while others are accessible without logging in.
              </li>
              <li>
                {" "}
                View Posts: Users can view posts created by other users.{" "}
              </li>
              <li>
                Create, Update, Delete Posts: Authenticated users can create new
                posts, update their own posts, and delete their posts.{" "}
              </li>
              <li>
                {" "}
                Like, Unlike Posts: Authenticated users can like and unlike
                posts.{" "}
              </li>
              <li>
                Commenting: Users can leave comments on posts, edit their
                comments, and delete comments.
              </li>
              <li>
                {" "}
                Profile Management: Users can edit their profiles, change
                avatars, bios, and basic information.{" "}
              </li>
              <li>
                View Others&apos; Profiles: Users can view profiles of other
                users to learn more about them.
              </li>
              <li>
                {" "}
                UI Using Chakra UI: The user interface is designed using Chakra
                UI, providing a modern and responsive design.{" "}
              </li>
              <li>
                GraphQL Client: Utilizes a GraphQL client to interact with the
                backend API.
              </li>
            </ul>

            <a
              href="https://gql-blogging-website-client.vercel.app"
              rel="noreferrer"
              target="_blank"
            >
              <button className="px-8 py-2 mt-4 mr-8 hover:scale-105 duration-300">
                Demo
              </button>
            </a>
            <a
              href="https://github.com/pawpaw2022/gql-blogging-website-client"
              rel="noreferrer"
              target="_blank"
            >
              <button className="px-8 py-2 mt-4 hover:scale-105 duration-300">
                Code
              </button>
            </a>
          </div>
        </div>

        <div className="lg:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 duration-200 mx-4 lg:mx-0">
          <div className="p-2">
            <p className="text-center font-bold pb-2">Technologies</p>
            <div className="grid grid-cols-3 lg:grid-cols-1">
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Typescript
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> React 18
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Chakra UI
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> GraphQL
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Apollo Server
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Prisma ORM
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> MySQL
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Redis
              </p>
            </div>
          </div>
        </div>

        <div>
          <Link href="/#projects">
            <p className="py-2 text-gray-600 underline cursor-pointer">Back</p>
          </Link>
        </div>
      </div>
    </div>
  );
}

export default Facebowl;
