/** @format */

import React from "react";
import Image from "next/image";
import { IoMdRadioButtonOn } from "react-icons/io";
import Link from "next/link";
import Head from "next/head";
import { NotificationManager } from "react-notifications";
import { NotificationContainer } from "react-notifications";

function Simplebank() {
  return (
    <div className="w-full">
      <Head>
        <title>Paul | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://toppng.com/uploads/preview/alien-11569184369mxcbuyahny.png"
        />
      </Head>
      <div className="w-screen h-[30vh] lg:h-[40vh] relative">
        <div className="absolute top-0 w-full h-[30vh] lg:h-[40vh] bg-black/80 z-10" />
        <Image
          className="absolute z-[-1]"
          layout="fill"
          ƒ
          objectFit="cover"
          src="/showcases/simplebank.png"
          alt="/netflix-showcase"
        />
        <div className="absolute top-[70%] max-w-[1240px] w-full translate-y-[-50%] text-white p-4 z-10">
          <h2 className="py-2">SimpleBank Backend System</h2>
          <h3>
            Go / Gin / Postgres / Github Actions / Docker / AWS / Kubernetes
          </h3>
        </div>
      </div>

      <div className="max-w-[1240px] p-2 grid lg:grid-cols-5 gap-8 pt-8 mx-6">
        <div className="lg:col-span-4">
          <p className="text-xl tracking-wider uppercase text-[#5651e5]">
            Project
          </p>
          <h2 className="py-2 text-gray-600">Overview</h2>
          <p className="py-2 text-gray-600">
            The Simple Banking System is designed to provide basic banking
            functionalities, including user sign-up, login, account creation,
            and money transfers between accounts.
          </p>

          <h2 className="py-2 text-gray-600 text-2xl">Features</h2>
          <ul className="list-disc ml-5">
            <li>
              <h4>Database (DB)</h4>
              <ul className="list-disc ml-5">
                <li>Primary database: PostgreSQL</li>
                <li>SQL generation: sqlc</li>
                <li>Unit testing: Go testing package</li>
                <li>
                  Transaction handling: Database transactions for atomic actions
                </li>
                <li>
                  Continuous integration (CI): GitHub Actions for automated
                  testing with Go and PostgreSQL
                </li>
              </ul>
            </li>
            <li>
              <h4>REST APIs</h4>
              <ul className="list-disc ml-5">
                <li>
                  Framework: Gin (a popular Go framework for building APIs)
                </li>
                <li>Configuration: Viper for loading configuration</li>
                <li>
                  Integration testing: Mock DB for comprehensive test coverage
                </li>
                <li>Password hashing: Bcrypt for secure password storage</li>
                <li>Authentication: PASETO tokens for enhanced security</li>
                <li>
                  Middleware: Authentication middleware to protect specific
                  routes
                </li>
              </ul>
            </li>
            <li>
              <h4>Deployment</h4>
              <ul className="list-disc ml-5">
                <li>Docker: Build Docker images for the application</li>
                <li>Docker Compose: Orchestrating DB and API server startup</li>
                <li>
                  Continuous integration (CI): GitHub Actions for building and
                  pushing images to AWS ECR
                </li>
                <li>Database migration: Migrate local DB to AWS RDS</li>
                <li>Environment variables: Stored in AWS Secret Manager</li>
                <li>
                  Kubernetes: AWS EKS for container orchestration, managed with
                  kubectl and k9s
                </li>
                <li>Custom domain: Achieved using AWS Route 53</li>
                <li>
                  Traffic routing: Kubernetes Ingress for directing traffic to
                  different services
                </li>
                <li>
                  TLS security: Let&apos;s Encrypt for obtaining and renewing
                  free SSL/TLS certificates
                </li>
                <li>
                  Continuous deployment (CD): GitHub Actions for deploying new
                  commits to Kubernetes
                </li>
              </ul>
            </li>
          </ul>

          <button
            className="px-8 py-2 mt-4 mr-8 hover:scale-105 duration-300"
            onClick={() => {
              NotificationManager.warning(
                "As of 2023-09-01, the service of this project will be terminated from AWS as EKS is too expensive to maintain. The project is meant to be a learning experience and not a production-ready application.",
                "Announcement",
                10000
              );
            }}
          >
            Demo
          </button>

          <a
            href="https://github.com/pawpaw2022/simplebank/"
            rel="noreferrer"
            target="_blank"
          >
            <button className="px-8 py-2 mt-4 hover:scale-105 duration-300">
              Code
            </button>
          </a>
        </div>

        <div className="lg:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 duration-200 mx-4 lg:mx-0">
          <div className="p-2">
            <p className="text-center font-bold pb-2">Technologies</p>
            <div className="grid grid-cols-3 lg:grid-cols-1">
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Go 1.20
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> PostgreSQL
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> SQLC
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Github Actions
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Gin
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Mock DB
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> PASETO
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Docker
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Kubernetes
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> AWS ECR
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> AWS RDS
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> AWS EKS
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> AWS Route 53
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> TLS Certificate
              </p>
            </div>
          </div>
        </div>

        <div>
          <Link href="/#projects">
            <p className="py-2 text-gray-600 underline cursor-pointer">Back</p>
          </Link>
        </div>
      </div>
      <NotificationContainer />
    </div>
  );
}

export default Simplebank;
