/** @format */

import React from "react";
import Image from "next/image";
import { IoMdRadioButtonOn } from "react-icons/io";
import Link from "next/link";
import Head from "next/head";

function Simplebank() {
  return (
    <div className="w-full">
      <Head>
        <title>Paul | Front-End Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://toppng.com/uploads/preview/alien-11569184369mxcbuyahny.png"
        />
      </Head>
      <div className="w-screen h-[30vh] lg:h-[40vh] relative">
        <div className="absolute top-0 w-full h-[30vh] lg:h-[40vh] bg-black/80 z-10" />
        <Image
          className="absolute z-[-1]"
          layout="fill"
          ƒ
          objectFit="cover"
          src="/showcases/simplebank.png"
          alt="/netflix-showcase"
        />
        <div className="absolute top-[70%] max-w-[1240px] w-full translate-y-[-50%] text-white p-4 z-10">
          <h2 className="py-2">SimpleBank Backend System</h2>
          <h3>
            Go / Gin / Postgres / Github Actions / Docker / AWS / Kubernetes
          </h3>
        </div>
      </div>

      <div className="max-w-[1240px] p-2 grid lg:grid-cols-5 gap-8 pt-8 mx-6">
        <div className="lg:col-span-4">
          <p className="text-xl tracking-wider uppercase text-[#5651e5]">
            Project
          </p>
          <h2 className="py-2 text-gray-600">Overview</h2>
          <p className="py-2 text-gray-600">
            A simple to-do list app built with vanilla JavaScript. Just like any
            other beginner who just started to learn coding, I chose this app to
            strengthen the fundementals. But unlike any other to-do lists that
            you can easily find on the internet, I added some
            <span className="text-[#5651e5] font-bold uppercase">
              {" "}
              special sauce{" "}
            </span>{" "}
            to stand out from the crowd.
          </p>

          <h2 className="py-2 text-gray-600 text-2xl">Features</h2>
          <ul className="list-disc ml-5">
            <li>Allow Create/Delete a To-Do on the task board.</li>
            <li>Allow Drag-n-Drop to sort the To-Dos.</li>
            <li className="text-[#5651e5]">
              Use trigonometry to calculate the angle so the Simpson&apos;s
              eyeballs will always follow the mouse cursor.
            </li>
          </ul>

          <a
            href="https://lucent-tulumba-bce44d.netlify.app/"
            rel="noreferrer"
            target="_blank"
          >
            <button className="px-8 py-2 mt-4 mr-8 hover:scale-105 duration-300">
              Demo
            </button>
          </a>
          <a
            href="https://github.com/pawpaw2022/vanilla-todo-list"
            rel="noreferrer"
            target="_blank"
          >
            <button className="px-8 py-2 mt-4 hover:scale-105 duration-300">
              Code
            </button>
          </a>
        </div>

        <div className="lg:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4 hover:scale-105 duration-200 mx-4 lg:mx-0">
          <div className="p-2">
            <p className="text-center font-bold pb-2">Technologies</p>
            <div className="grid grid-cols-3 lg:grid-cols-1">
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> HTML5
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> Sass
              </p>
              <p className="flex text-gray-600 py-2 items-center">
                <IoMdRadioButtonOn className="pr-1" /> JavaScript
              </p>
            </div>
          </div>
        </div>

        <div>
          <Link href="/#projects">
            <p className="py-2 text-gray-600 underline cursor-pointer">Back</p>
          </Link>
        </div>
      </div>
    </div>
  );
}

export default Simplebank;
